### ISSUE TITLE
Usage page has broken link to "example samplesheet"

### ISSUE THREAD

**Issue by alanhoyle** [nf-core/rnadnavar#19]
### Description of the bug

There is an issue with the documentation here:

https://nf-co.re/rnadnavar/dev/docs/usage

has a link titled "example samplesheet" that goes to https://nf-co.re/rnadnavar/dev/assets/samplesheet.csv

That link is broken.  

I see multiple CSV files in https://github.com/nf-core/rnadnavar/tree/dev/assets but I'm not sure which one is intended to be the link.  the simplest one, samplesheet.csv seems to lack most of the columns that one would expect from the rest of the documentation.  

### Command used and terminal output

```console
n/a
```

### Relevant files

n/a

### System information

n/a

**Comment by RaqManzano** [comment]
Thanks, absolutely right. Working on it, things will make more sense once there is a first release.
