### ISSUE TITLE
not found http???

### ISSUE THREAD

**Issue by torres-HI** [nf-core/rnadnavar#39]
### Description of the bug

Ho someone was available to used this pipeline??

can you tell me how do it?

thank you

[rnadnavar](https://github.com/nf-core/rnadnavar)
Pulling nf-core/rnasdnavar ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/rnasdnavar/contents/nextflow.config?ref=dev

Pulling nf-core/rnasdnavar ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/rnasdnavar/contents/nextflow.config?ref=dev

### Command used and terminal output

```console
[rnadnavar](https://github.com/nf-core/rnadnavar)
Pulling nf-core/rnasdnavar ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/rnasdnavar/contents/nextflow.config?ref=dev

Pulling nf-core/rnasdnavar ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/rnasdnavar/contents/nextflow.config?ref=dev
```

**Comment by maxulysse** [comment]
Hi, this looks like a typo:
`nf-core/rnasdnavar` instead of `nf-core/rnadnavar`

**Comment by torres-HI** [comment]
thank you

**Comment by torres-HI** [comment]
thank you
